[platformio]
core_dir = ../.platformio-core

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_upload.flash_size = 2MB
upload_port = COM7
monitor_port = COM7
monitor_speed = 115200
